const IELTS_FILL_BLANKS = [
  ["The professor's ___ analysis of the data revealed patterns that had eluded previous researchers.","meticulous","superficial","negligent","perfunctory"],
  ["The politician attempted to ___ the scandal by diverting attention to economic issues.","obfuscate","elucidate","illuminate","clarify"],
  ["Despite the ___ evidence, the jury found the defendant not guilty.","overwhelming","scanty","negligible","trifling"],
  ["The scientist's ___ theory challenged decades of established research in the field.","iconoclastic","orthodox","conventional","traditional"],
  ["The diplomat's ___ demeanor helped ease tensions during the delicate negotiation.","conciliatory","confrontational","bellicose","belligerent"],
  ["The author's ___ writing style has been praised for its clarity and precision.","succinct","verbose","prolix","circuitous"],
  ["Economic inequality remains a ___ issue that policymakers have struggled to address.","pervasive","sporadic","intermittent","fleeting"],
  ["The philosopher argued that morality is not ___ but evolves with society.","immutable","malleable","pliable","transient"],
  ["Her ___ optimism was remarkable given the severity of the challenges she faced.","indefatigable","ephemeral","desultory","capricious"],
  ["The company's ___ practices led to its eventual bankruptcy.","unscrupulous","meticulous","scrupulous","conscientious"],
  ["The historian sought to ___ the myth from historical fact through rigorous archival research.","disentangle","perpetuate","embellish","conflate"],
  ["A ___ of errors in the financial report raised serious concerns among the auditors.","plethora","dearth","paucity","scarcity"],
  ["The ambassador's ___ remarks inadvertently offended the host nation.","indiscreet","diplomatic","circumspect","prudent"],
  ["Climate scientists warn that the window for action is growing ___ narrow.","perilously","comfortably","reassuringly","negligibly"],
  ["The novel offers a ___ critique of contemporary consumer culture.","trenchant","superficial","perfunctory","desultory"],
  ["The ancient manuscript had survived centuries in ___ condition.","pristine","dilapidated","decrepit","ramshackle"],
  ["Her argument was ___ by a lack of empirical evidence.","undermined","corroborated","substantiated","bolstered"],
  ["The CEO's ___ leadership style alienated many talented employees.","imperious","egalitarian","democratic","collegial"],
  ["The research team made a ___ discovery that transformed the field of genetics.","seminal","trivial","inconsequential","marginal"],
  ["Political polarization has ___ to such an extent that meaningful dialogue is increasingly rare.","intensified","diminished","attenuated","dissipated"],
  ["The anthropologist documented the ___ customs of the indigenous communities.","idiosyncratic","ubiquitous","universal","mundane"],
  ["His ___ response to the crisis was widely praised by international observers.","judicious","reckless","impetuous","rash"],
  ["The diplomat sought to ___ the conflict before it escalated into a full-scale war.","defuse","exacerbate","inflame","aggravate"],
  ["A ___ silence fell over the courtroom as the verdict was announced.","palpable","imperceptible","intangible","ethereal"],
  ["The report ___ the government's failure to address systemic inequality.","excoriated","commended","lauded","applauded"],
  ["Urban planners must ___ economic development with environmental sustainability.","reconcile","antagonize","estrange","alienate"],
  ["The witness gave a ___ account of the events leading up to the incident.","coherent","convoluted","discordant","incongruous"],
  ["Antibiotic resistance poses a ___ threat to global public health.","formidable","negligible","inconsequential","trifling"],
  ["The writer's ___ observations about human nature resonated with readers across generations.","sagacious","fatuous","vacuous","insipid"],
  ["Several factors ___ to create the perfect conditions for economic collapse.","coalesced","diverged","dispersed","dissipated"],
  ["The judge ___ the defendant's argument as legally baseless.","repudiated","endorsed","ratified","validated"],
  ["A ___ of rainfall during the growing season led to widespread crop failure.","dearth","surfeit","abundance","plethora"],
  ["The peace treaty was ___ and did little to resolve the underlying tensions.","cosmetic","substantive","fundamental","profound"],
  ["Her ___ enthusiasm for the project inspired the entire team.","ebullient","tepid","lukewarm","indifferent"],
  ["The methodology was ___ because it failed to control for key variables.","fallacious","robust","rigorous","sound"],
  ["Critics argue that the legislation will ___ rather than alleviate the housing crisis.","exacerbate","mitigate","ameliorate","palliate"],
  ["The memoir offers a ___ glimpse into the author's troubled childhood.","poignant","insipid","vapid","prosaic"],
  ["The general's ___ strategy caught the enemy completely off guard.","audacious","timid","pusillanimous","circumspect"],
  ["Scholars continue to debate the ___ significance of the archaeological findings.","putative","undeniable","incontrovertible","indisputable"],
  ["The ___ between theoretical physics and experimental results has widened considerably.","chasm","nexus","symbiosis","confluence"],
];
